site_name: optionslib_java
site_url: https://github.com/dkrajzew/optionslib_java
site_description: A java library for parsing command line options, supporting type-checking and configurations
site_author: Daniel Krajzewicz
docs_dir: ./docs

repo_url: https://github.com/dkrajzew/optionslib_java.git
edit_uri: ""

theme:
    name: material
    custom_dir: ./docs/materials_ext
    font: false
    palette:
        primary: blue
        
extra_css:
    - stylesheets/extra.css
    - stylesheets/prism.css

extra_javascript:
    - js/prism.js

nav:
    - Home: index.md
    - Usage: Usage.md
    - Building: Building.md
    - Applications: Applications.md
    - ChangeLog: ChangeLog.md
    - License (BSD): license.md
    - Disclaimer: Disclaimer.md
    - Meta: Meta.md

exclude_docs:

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2020&ndash;2024 Daniel Krajzewicz."

use_directory_urls: false
